name: Generate PEGS Documentation

# Déclenchement : à chaque push sur la branche main
on:
  push:
    branches: ["main"]
    paths:
      - '**/*.adoc' # Ne se lance que si un fichier .adoc est modifié
  workflow_dispatch: # Permet de lancer manuellement si besoin

# Permissions nécessaires pour publier sur GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Une seule tâche qui gère la concurrence
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de construction (Build)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Asciidoctor & PDF
        # CORRECTION ICI : On utilise 'gem' pour installer le convertisseur PDF
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full graphviz
          sudo gem install asciidoctor asciidoctor-pdf

      - name: Convert Adoc to HTML & PDF
        run: |
          # --failure-level WARN : La CI plante si un fichier include est manquant ou si la syntaxe est mauvaise
          asciidoctor requirements.adoc -o index.html
          asciidoctor-pdf requirements.adoc -o specifications.pdf

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  # Job de déploiement (Deploy)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4