name: Generate PEGS Documentation

# Déclenchement : à chaque push sur la branche main
on:
  push:
    branches: ["main"]
    paths:
      - '**/*.adoc' # Ne se lance que si un fichier .adoc est modifié
  workflow_dispatch: # Permet de lancer manuellement si besoin

# Permissions nécessaires pour publier sur GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Une seule tâche qui gère la concurrence
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de construction (Build)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 🧪 Test - Check Mandatory PEGS Files
        run: |
          files=(
            "Docs/Project/p3-schedule_and_milestones.adoc"
            "Docs/Project/p4-tasks_and_deliverables.adoc"
            "Docs/Goals/g1-context_and_overall_objectives.adoc"
            "Docs/Goals/g3-expected_benefits.adoc"
            "Docs/Goals/g7-stakeholders_and_sources.adoc"
            "Docs/Environment/e3-constraints.adoc"
            "Docs/System/s1-components.adoc"
            "Docs/System/s2-functionality.adoc"
          )

          has_error=0

          echo "🔍 Vérification des fichiers obligatoires..."

          for file in "${files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ ERREUR: Fichier manquant -> $file"
              has_error=1
            elif [ ! -s "$file" ]; then
              echo "❌ ERREUR: Fichier vide -> $file"
              has_error=1
            else
              echo "✅ OK: $file"
            fi
          done

          if [ $has_error -eq 1 ]; then
            echo "⛔ Le test a échoué. Certains fichiers obligatoires sont manquants ou vides."
            exit 1
          fi

      - name: Install Asciidoctor & PDF
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full graphviz
          sudo gem install asciidoctor asciidoctor-pdf

      - name: Convert Adoc to HTML & PDF
        run: |
          asciidoctor --failure-level WARN requirements.adoc -o index.html
          asciidoctor-pdf --failure-level WARN requirements.adoc -o specifications.pdf

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  # Job de déploiement (Deploy)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4